import express from "express";
import adminController from "../controllers/adminController.js";
const adminRouter = express.Router();
adminRouter.get("/", adminController.panel);
adminRouter.get("/regrab", adminController.getTypeDay);
adminRouter.post("/regrab", adminController.addTypeDay);
adminRouter.get("/calendar", adminController.listCalendarItem);
adminRouter.post("/calendar", adminController.addCalendarItem);
adminRouter.delete("/delcalendaritem/:id", adminController.delCalendarItem);
adminRouter.get("/addnews", adminController.formaddnews);
adminRouter.post("/addnews", adminController.addNews);
adminRouter.delete("/delnews/:id", adminController.delNews);
adminRouter.get("/listnews", adminController.getListNews);
adminRouter.put("/savechangesnews", adminController.saveChangesNews);
adminRouter.get("/login", adminController.login);
adminRouter.post("/login", adminController.loginIn);
adminRouter.get("/listregistration", adminController.getListRegistration);
adminRouter.delete("/delregistration/:id", adminController.delRegistration);
export default adminRouter;
